Added new OS wallpaper
catppuccin/wallpapers pull request #67
Opened 2023-03-16 19:13 UTC by ItsHoul

2023-03-22 10:52 UTC, dscoder421 requested changes
I think the colour for the O is a bit off, and is not in the Catppuccin pallete

2023-03-22 10:55 UTC, ItsHoul commented
> I think the colour for the O is a bit off, and is not in the Catppuccin pallete

the O should be fine, maybe it's just the font

and i picked colours from other wallpapers in this repo so idk

2023-03-23 05:17 UTC, dscoder421 commented
It actually looks great @ItsHoul, approved it!

On Wed, Mar 22, 2023 at 4:26 PM Houl ***@***.***> wrote:

> I think the colour for the O is a bit off, and is not in the Catppuccin
> pallete
>
> the O should be fine, maybe it's just the font
>
> and i picked colours from other wallpapers in this repo so idk
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/catppuccin/wallpapers/pull/67#issuecomment-1479347709>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMA2OB3X22KAXSCFWUDEFSDW5LLD7ANCNFSM6AAAAAAV5UD6PI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-03-23 05:18 UTC, dscoder421 approved these changes

2023-03-26 13:36 UTC, closed without merging